# Generated by Django 5.2 on 2025-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_companyprofile_studentprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="student_id",
            new_name="graduation_year",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="given_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="major_chosen",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="transcript",
            field=models.FileField(blank=True, null=True, upload_to="transcripts/"),
        ),
    ]
