# Generated by Django 5.2 on 2025-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_student_id_studentprofile_graduation_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="teacher_id",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_office_first_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_office_first_images/"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_office_second_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_office_second_images/"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_office_third_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_office_third_images/"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="job_internship_vancancy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
