# Generated by Django 5.2 on 2025-09-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_company_to_professor'),
    ]

    operations = [
    ]
