# Generated by Django 5.2 on 2025-09-09 10:12

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_company_to_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('professors', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='professorprofile',
            name='team_image',
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='professor_profile_images/'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='lab_first_image',
            field=models.FileField(blank=True, null=True, upload_to='professor_lab_images/'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='lab_second_image',
            field=models.FileField(blank=True, null=True, upload_to='professor_lab_images/'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='lab_third_image',
            field=models.FileField(blank=True, null=True, upload_to='professor_lab_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('PROFESSOR', 'Professor')], default='ADMIN', max_length=50),
        ),
    ]
